<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKHis5EU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKHis5EU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKHis5EU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKHis5EU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKHis5EU\App_KernelDevDebugContainer([
    'container.build_hash' => 'KHis5EU',
    'container.build_id' => '1f80889f',
    'container.build_time' => 1581010698,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKHis5EU');
